### ISSUE TITLE
Docker image seems to be missing from Dockerhub

### ISSUE THREAD

**Issue by drew12341** [getml/getml-community#2]
Hi there - just a quick message to let you know that the dockerimage appears to be missing.  Thanks

**Comment by liuzicheng1987** [comment]
Hi @drew12341 , sorry that it took me a while to respond.

We just provide the Dockerfile which you can then use to build the Docker image yourself. 

Like it says in the README:

1. Download the ZIP file. Unzip it.
2. cd into the folder that was created by unzipping the ZIP file.
3. Run ./setup.sh. This will build the image for you.

**Comment by liuzicheng1987** [comment]
@drew12341 , I just tried it on my Mac, just to be sure that it works. It works beautifully.
<img width="2999" alt="截圖 2023-07-19 22 03 08" src="https://github.com/getml/getml-community/assets/19538706/83ac58b2-3069-446b-9918-7e7e086ee10c">
<img width="1415" alt="截圖 2023-07-19 22 03 36" src="https://github.com/getml/getml-community/assets/19538706/5ee08ea4-de8e-4da4-ab48-a0dc1a338005">
<img width="1701" alt="截圖 2023-07-19 22 03 55" src="https://github.com/getml/getml-community/assets/19538706/c94b2a44-6858-4a2b-8e04-09c4f75341ff">

**Comment by liuzicheng1987** [comment]
But thanks for your feedback. Maybe we should include these kind of screenshots in the README as well.
