### ISSUE TITLE
select via boolean list or array on DataFrame

### ISSUE THREAD

**Issue by joro-enbw** [getml/getml-community#6]
Currently we can only select rows from a DataFrame via a BooleanColumnView.

Support for selection via list of bools or numpy array of bools should be added.

```
target_table[list_or_numpy_array_of_bools]
```

**Comment by liuzicheng1987** [comment]
This is very difficult from a practical point of view, because views are always lazily evaluated and they do not contain any data. But this is contradicted by the requirement, because this would require us to upload data to the engine.
