### ISSUE TITLE
Tetouan city is a Moroccan city

### ISSUE THREAD

**Issue by ImadSaddik** [getml/getml-community#8]
Hello, while reading the README.md, I saw that there is a mistake. Here is the original text `Tetouan | Ten-minute electricity consumption of three different zones in Tetouan City, Mexico`. But Tetouan is a Moroccan city, not a Mexican city.

A small issue, I know ;)

**Comment by Urfoex** [comment]
Thank you @ImadSaddik  for pointing it out. We will fix it shortly.

**Comment by srnnkls** [comment]
Fixed with 1.5.0 just released.

**Comment by ImadSaddik** [comment]
Thank you.
